### DISCUSSION TITLE
The gtctl how to open dashboard at startup

### DISCUSSION THREAD

**Discussion by leaf-potato** [GreptimeTeam/greptimedb#4566] [Q&A] [answered]
Start with `gtctl playground` command, access the dashboard ok: 

<img width="2037" alt="image" src="https://github.com/user-attachments/assets/b0d64e3b-8261-48c2-8bad-d6ffade5464a">

However, when I use this command  `gtctl cluster create dev --bare-metal --config config.yaml` to create a local cluster, access the dashboard failed: 

<img width="2041" alt="image" src="https://github.com/user-attachments/assets/23a8b56d-3d8b-46b0-a930-fda67449aa39">

config.yaml: 
```yaml
cluster:
  name: dev
  artifact:
    local: "./target/debug/greptime"
  frontend:
    replicas: 1
    httpAddr: 0.0.0.0:4000
  datanode:
    replicas: 1
    rpcAddr: 0.0.0.0:14100
    mysqlAddr: 0.0.0.0:14200
    httpAddr: 0.0.0.0:14300
  meta:
    replicas: 1
    storeAddr: 127.0.0.1:2379
    serverAddr: 0.0.0.0:3002
    httpAddr: 0.0.0.0:14001

etcd:
  artifact:
    version: v3.5.7
```

Wondering if a separate configuration is needed or If this is a bug.
