### DISCUSSION TITLE
Graph from greptime intermittent on Grafana

### DISCUSSION THREAD

**Discussion by itestrada** [GreptimeTeam/greptimedb#6313] [Q&A]
data from greptime when pulled in grafana there is intermittent on the graphic

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/fc619db9-3ee3-41eb-9f3b-31e45f31b8fe" />

i have compare with graph that i pulled from prometheus

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/59d545ab-5e35-45c4-a6e1-87e54010cf67" />

**Comment by daviderli614** [comment]
Hello, can you provide more details? For example, deployment and configuration, greptime version.
Is it currently written to greptime through prometheus remote write? You can check the prometheus and greptime log to see if there are any errors.

Try to improve the prometheus remote write queue configuration: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
```
          queue_config:
            capacity: 10000
            minShards: 1
            maxShards: 50
            maxSamplesPerSend: 20000
            batchSendDeadline: 20s
            minBackoff: 1s
            maxBackoff: 8s
```


Can you configure greptime metrics here: https://github.com/GreptimeTeam/greptimedb/tree/main/grafana/dashboards/metrics

In addition, these graph are different time in prometheus and greptime(start time -> end time).
