### ISSUE TITLE
Make log level and destination configurable from config files

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1313]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

At the moment it seems log configuration can only be specified from command-line interface. This can be inconvenience when deploying greptime as a service.

Expected behaviour:

Add `logging` section in toml configuartion:

```toml
[logging]
level = "debug"
dir = "/var/lib/greptimedb/log"
```
