### ISSUE TITLE
Expose ManifestLogStorage compress configuration to user

### ISSUE THREAD

**Issue by Taylor-lagrange** [GreptimeTeam/greptimedb#1561]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

Manifest log now supports compression but it is not enabled by default. I hope to expose the option to users whether to enable Manifest log compression.

expose a config `use_compress` to user whether to use Manifest log compression.

```toml
[storage.manifest]
checkpoint_on_startup = true
use_compress = true # false by default
```

Related Issue and PR are here
https://github.com/GreptimeTeam/greptimedb/issues/1394
https://github.com/GreptimeTeam/greptimedb/pull/1497
