### ISSUE TITLE
Refactor: move heartbeat configuration into an independent section in config file

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1936]
### What type of enhancement is this?

Configuration, User experience

### What does the enhancement do?

The PR #1864 has introduced two new parameters to control heartbeat:

```toml
# Interval for sending heartbeat task to the Metasrv in milliseconds, 5000 by default.
heartbeat_interval_millis = 5000
# Interval for retry sending heartbeat task in milliseconds, 5000 by default.
retry_interval_millis = 5000
```

I think they must be moved into an independent section of the config file such as `meta` or `heartbeat`:

```toml
[meta]
# Interval for sending heartbeat task to the Metasrv in milliseconds, 5000 by default.
heartbeat_interval_millis = 5000
# Interval for retry sending heartbeat task in milliseconds, 5000 by default.
retry_interval_millis = 5000
```

And they don't need to be present in standalone mode.
