### ISSUE TITLE
Unify setting the options for the object store's http client

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#4907]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

Now the options for the object store's http client are set like this:

```rust
let connect_timeout = env::var("_GREPTIMEDB_HTTP_CONNECT_TIMEOUT")
    .ok()
    .and_then(|v| v.parse::<u64>().ok())
    .unwrap_or(30);
builder = builder.connect_timeout(Duration::from_secs(connect_timeout));
```

It's better to make them set from the config file instead, like this:

```toml
[[storage.providers]]
name = "S3"
type = "S3"
timeout = "30s"
# ...
```
