### ISSUE TITLE
Pipeline dispatcher

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#5326]
### What problem does the new feature solve?

Currently we can store all the logs/events from one API call to a single table. However, it's possible that several different types of logs share the same source. 

### What does the feature do?

So in our pipeline, we need a mechanism to dispatch data into different pipelines, and eventually different tables, based on certain fields like `type`, or any other data that user can extract from the pipeline.

```yaml
processors:

dispatcher:
  field: type
  routes:
    - value: http
      pipeline: http_pipeline
      table_name: ${prefix}_http
    - value: database
      pipeline: database_pipeline
      table_name: ${prefix}_database
    - default: yes
      pipeline: default_pipeline
      table_name: ${prefix}_events
```

```mermaid
flowchart TD
    A[entry_pipeline] --> D(dispatcher)
    D --> |type=http| B[http_pipeline]
    D --> |type=database| C[database_pipeline]
    D --> |type=unknown| E[default_pipeline]
```
