### ISSUE TITLE
Table options not available in CREATE DATABASE

### ISSUE THREAD

**Issue by emliunix** [GreptimeTeam/greptimedb#5549]
### What type of bug is this?

Configuration

### What subsystems are affected?

Standalone mode, Metasrv

### Minimal reproduce step

It's mentioned in [doc](https://docs.greptime.com/reference/sql/create#create-database) table options are applicable to CREATE DATABSE WITH as well, but the [code](https://github.com/GreptimeTeam/greptimedb/blob/8026b1d/src/sql/src/parsers/create_parser.rs#L61) suggests it's hard coded to allow only TTL.

Execute the following SQL.

```
create database log with (ttl = '7d', storage = 's3');
```

```toml
# config file
[storage]
type = "File"
data_home = "/var/lib/greptimedb"
cache_path = "/var/lib/greptimedb/cache"
cache_capacity = "2GiB"

[wal]
dir = "/var/lib/greptimedb/wal"

[logging]
dir = "/var/lib/greptimedb/log"

[[storage.providers]]
name = "s3"
type = "S3"
# more s3 configs redacted
```

### What did you expect to see?

database created with default storage options.

### What did you see instead?

```
11:31:35 PM [error] create database log with (ttl = '7d', storage = 's3'); Unrecognized database option key: storage
```

### What operating system did you use?

docker.io/greptime/greptimedb:v0.11.3 on arm64 orangepi 5 pro

### What version of GreptimeDB did you use?

v0.11.3

### Relevant log output and stack trace

```bash

```
