### ISSUE TITLE
Confusing error `Can not coerce json type to json`

### ISSUE THREAD

**Issue by vbmithr** [GreptimeTeam/greptimedb#5934]
### What type of bug is this?

User Experience

### What subsystems are affected?

Frontend, Standalone mode

### Minimal reproduce step

Pipe this input:

```
{"host":"sita","message":"{\"ts\":1744882691116184,\"data\":{\"stream\":\"bnbusdc@depth@100ms\",\"data\":{\"e\":\"depthUpdate\",\"E\":1744882691008,\"T\":1744882690907,\"s\":\"BNBUSDC\",\"U\":7294819079480,\"u\":7294819079480,\"pu\":7294819074877,\"b\":[[\"583.770\",\"2.57\"],[\"585.250\",\"13.46\"]],\"a\":[]}}}","source_type":"stdin","timestamp":1744963375149882}
```

with this pipeline:

```
transform:
  # Timestamp field
  - fields:
      - ts
    type: epoch, us
    index: timestamp
  # fhid/xch/stream (tags), i.e. identifying only one time series.
  - fields:
      - fhid
    type: uint8
    tag: true
    on_failure: default
    default: 0
  - fields:
      - xch
    type: string
    tag: true
    index: inverted
  - fields:
      - stream
    type: string
    tag: true
    index: inverted
  # Payload
  - fields:
      - message
    type: json
```

### What did you expect to see?

The pipeline assumed the message was just the field `message` where Vector added the other fields.

In log namespacing mode (new feature in Vector) I have the control of exactly what will be output (no automatic adding of fields in the message) and my input has the right format for the pipeline.

So I guess what happens here is that Greptime sees a string instead of JSON for the `message` field, and print this error. Didn't get the time to dig further.

### What did you see instead?

Confusing error:

```
Can not coerce json type to json, at src/pipeline/src/etl/transform/transformer/greptime/coerce.rs:442:10
```

### What operating system did you use?

Archlinux

### What version of GreptimeDB did you use?

0.14

### Relevant log output and stack trace

```bash

```
