### ISSUE TITLE
Large memory usage when feeding logs through a pipeline

### ISSUE THREAD

**Issue by vbmithr** [GreptimeTeam/greptimedb#6277]
### What type of bug is this?

Performance issue

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

```yaml
processors:
  - vrl:
      source: |
        .xch = "BFU"
        .stream = .data.stream
        .message = .data
        del(.data)
        .

transform:
  # Timestamp field
  - fields:
      - ts
    type: epoch, us
    index: timestamp
  # fhid/xch/stream (tags), i.e. identifying only one time series.
  - fields:
      - xch
    type: string
    tag: true
    index: inverted
  - fields:
      - stream
    type: string
    tag: true
    index: inverted
  # Payload
  - fields:
      - message
    type: json
```

```shell
curl "http://localhost:40000/v1/events/logs?table=stream_historical&pipeline_name=vrl&ignore_errors=false" \
         -H "Content-Type: application/x-ndjson" \
         -H "Content-Encoding: none" \
         --data-binary @2025-04-26_13-52-20.987442.raw
```

### What did you expect to see?

Program gets not OOMKILLed for 2GiB data of NDJSON on my 16GB RAM laptop.

### What did you see instead?

OOMKILL

### What operating system did you use?

Archlinux

### What version of GreptimeDB did you use?

0.15.0.20250609

### Relevant log output and stack trace

```bash

```
